### ISSUE TITLE
Error while executing make SIMULATION=native prep

### ISSUE THREAD

**Issue by PratikAher20** [cfs-tools/cfs-basecamp#17]
![IMG_20221221_171358](https://user-images.githubusercontent.com/106163261/208897943-93646c48-6671-48b0-ace4-8d836186795d.jpg)
What could the error?

**Comment by dmccomas** [comment]
I just cloned and got a different error captured below.  I just pushed some changes, cloned, and successfully built it.  I don't see any file differences that would explain the errors.

Can you please try again and see if it works.

![image](https://user-images.githubusercontent.com/1598728/209021603-2ef2b8d0-c16d-428c-af5b-56452ecf4dd2.png)

**Comment by PratikAher20** [comment]
Still getting the same error. " Object of target 'cfe_missionlib_python_pic' referenced but is not an OBJECT library. "

**Comment by dmccomas** [comment]
This is triggering a faint memory and the issue may be related to your
cmake version.   When I initially worked with the cfe-eds-framework
https://github.com/jphickey/cfe-eds-framework I may have had the same
issue. His website states "at least v2.8.12 recommended".  I'm using
cmake version 3.22.1.

What version of cmake do you have?

**Comment by PratikAher20** [comment]
I am using version 3.10.2 on ubuntu 18.04 LTS on VM as instructed for OpenSatKit in the installation video.

**Comment by dmccomas** [comment]
Basecamp and OpenSatKit are two different projects so the video technically
doesn't apply to Basecamp..  However, one of Basecamp's goals is to
minimize dependencies so it can run on as many platforms as possible. I
successfully built Basecamp on Ubuntu 22.04  and Ubuntu 20.04, but I get
the same error you do when I try Ubuntu 18.04. I'll keep looking into it.

**Comment by PratikAher20** [comment]
I am clear about the two different projects. Due to lack of resources I am using the same system for both OpenSatKit and cfs-Basecamp. 
Thanks for your support.

**Comment by dmccomas** [comment]
It does seem to be a cmake version issue based on the following [cmake objects of target X disucssion](https://discourse.cmake.org/t/objects-of-target-x-referenced-but-is-not-an-object-library/3857). Unfortunately, it looks like Ubuntu 18.04 may not support the cmake versions 3.12 of greater that is needed to remedy the issue.

**Comment by JiveyGuy** [comment]
I am in a similar situation. I was trying to use OpenSatKit and Basecamp on the same system. I will just install the correct version thanks for looking into this.

**Comment by dmccomas** [comment]
Basecamp uses [cfe-eds-framework](https://github.com/jphickey/cfe-eds-framework) that relies on a cmake version that must be at least v3.12 (This excludes Ubuntu 18.04 and earlier). This is noted on Basecamp's home page prerequisites, but I need to make it more prominent, because it gets lost in the notes. This is unfortunate because Ubuntu 18.04 is the last version of Ubuntu that OpenSatKit works on.  

The solution for Basecamp is to use a Linux platform that supports cmake version >= v3.12

The current long term OpenSatKit plan is to reduce its scope, so it serves as a cFS reference mission without any bells or whistles.  [OpenC3 COSMOS](https://openc3.com/) will be the ground system.

**Comment by JiveyGuy** [comment]
Making OSK purely reference cFS is a great goal, I look forward to seeing how it is done.
